require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ChatApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-doc-preview', :path => '../node_modules/react-native-doc-preview'

  target 'ChatAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChatApp-tvOS' do
  # Pods for ChatApp-tvOS

  target 'ChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
